### ISSUE TITLE
uefi无法启动windows

### ISSUE THREAD

**Issue by 4444w** [Afanyiyu/surface-pro-4-hackintosh-big-sur#12]
[点击查看动图](https://pan.whgpc.com/view.php/ed94ae78f5956cd8b255924df5bd7fd7.gif)
大佬帮忙看看这是咋回事，装好了mac，把你文件中的OC文件夹复制到EFI分区，用EasyUEFI添加了OC\OpenCore.efi启动项，开机的时候引导启动不了windows(看上图，mac启动正常，用u盘启动时也是引导启动不了Windows)
试过了v4 v5都不行，系统装的Monterey12.1

**Comment by ilharp** [comment]
README 里有写哦\~\~  可以参考 #3，需要自己 dump 一份新的 DSDT 的

如果你不太会 dump 的话可以先在 `config.plist` 把 DSDT 禁用掉

**Comment by 4444w** [comment]
> README 里有写哦~~ 可以参考 #3，需要自己 dump 一份新的 DSDT 的
> 
> 如果你不太会 dump 的话可以先在 `config.plist` 把 DSDT 禁用掉
提取了一个DSDT放进去可以启动windows了，就是mac看不见电量了😂😂

**Comment by 4444w** [comment]
t
