### ISSUE TITLE
surface pro4 mac os12 黑苹果apple ID和iCloud登录问题

### ISSUE THREAD

**Issue by DoctorWho1963** [Afanyiyu/surface-pro-4-hackintosh-big-sur#14]
登录时弹出窗口显示无法联系服务器的问题，网上教程说需要修改efi，我试了用opencore编译器修改config.plist，在PCI设备列表添加Ethernet开头的有线网卡设备信息，在DeviceProperties里添加built-in为01内建网卡的方法，但是还是没有解决。修改后并无异常。并且前后都可以用ID登录媒体与购买项目和App Store

**Comment by ilharp** [comment]
请参考 [Dortania 的官方教程](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html)~

**Comment by DoctorWho1963** [comment]
好的，非常感谢



---原始邮件---
发件人: "Il ***@***.***&gt;
发送时间: 2022年11月12日(周六) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ilharp/surface-pro-4-hackintosh-monterey] surface pro4 mac os12 黑苹果apple ID和iCloud登录问题 (Issue #14)




 
请参考 Dortania 的官方教程~

**Comment by DoctorWho1963** [comment]
n
你好，请问你的OC是什么版本?最新的open core configurator会提示版本低，我之前有个0.78的没有提示。



---原始邮件---
发件人: "Il ***@***.***&gt;
发送时间: 2022年11月12日(周六) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ilharp/surface-pro-4-hackintosh-monterey] surface pro4 mac os12 黑苹果apple ID和iCloud登录问题 (Issue #14)




 
请参考 Dortania 的官方教程~

**Comment by DoctorWho1963** [comment]
你好，请问你的OC是什么版本?最新的open core configurator会提示版本低，我之前有个0.76的没有提示。



---原始邮件---
发件人: "Il ***@***.***&gt;
发送时间: 2022年11月12日(周六) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ilharp/surface-pro-4-hackintosh-monterey] surface pro4 mac os12 黑苹果apple ID和iCloud登录问题 (Issue #14)




 
请参考 Dortania 的官方教程~

**Comment by DoctorWho1963** [comment]
已解决，可以使用Mac的迁移功能，将正常可登录的Mac系统数据迁移到新系统中解决。
