### ISSUE TITLE
in memory panic 

### ISSUE THREAD

**Issue by CXNB666** [Afanyiyu/surface-pro-4-hackintosh-big-sur#20]
![微信图片_20240303235936](https://github.com/ilharp/surface-pro-4-hackintosh-monterey/assets/94534463/c84f826e-c2f3-4041-9e50-c508b4bde404)
我不知道我的sp4 i5扩容前能不能用，但是扩容之后我找遍了任何的efi都会panic，商家扩了个pm991（怀疑这个硬盘问题）

**Comment by beckzhao0410** [comment]
我看了国光大神的硬盘支持列表，三星PM991应该是不支持的，你可以试下NVMeFix.kext 驱动，具体的看下截图
![7BBEB8D3BE-1EAE-48ce-BBAD-617B1E3907AA7D](https://github.com/ilharp/surface-pro-4-hackintosh-monterey/assets/62934437/7ad84032-0ac2-49f0-9757-cb7149c74a67)

**Comment by CXNB666** [comment]
好的谢谢

**Comment by CXNB666** [comment]
偶尔重启，其他没啥大问题
